### ISSUE TITLE
Timeout looking up document

### ISSUE THREAD

**Issue by dysbulic** [ceramicstudio/web-playground#12]
Currently, when attempting to load the page after connecting a wallet, a `GET` to [https://ceramic-clay.3boxlabs.com/api/v0/documents/k3y52l7qbv1fry8mks8g1azy3u04b0iigeljh06r7a8hacs360uw56zbqusw1e0hs](https://ceramic-clay.3boxlabs.com/api/v0/documents/k3y52l7qbv1fry8mks8g1azy3u04b0iigeljh06r7a8hacs360uw56zbqusw1e0hs) times out and the page dies.

I tried the code from #11, but got the `can't revolve multicodec/src/base-table.json` error and didn't pursue it further.

**Comment by oed** [comment]
Can you try running `npm list cids` and post the output?
